spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysqloc
    username: root
    password: x196414.
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com/layui/entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl